---
abstract: 'Authentication plugin for Opensso'
author:
  - 'Nito Martinez <Nito@Qindel.ES>'
build_requires:
  File::Spec: 0
  File::Temp: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: QVD-L7R-Authenticator-Plugin-Opensso
provides:
  QVD::L7R::Authenticator::Plugin::Opensso:
    file: lib/QVD/L7R/Authenticator/Plugin/Opensso.pm
    version: 0.03
requires:
  QVD::L7R: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.03
