build:

clean:

install:
	mkdir -p $(DESTDIR)/var/lib/qvd/storage/staging
	mkdir -p $(DESTDIR)/var/lib/qvd/storage/images
	mkdir -p $(DESTDIR)/var/lib/qvd/storage/overlays
	mkdir -p $(DESTDIR)/var/lib/qvd/storage/homes

