#!/bin/sh -e

if [ "$1" = "configure" ]; then
    MAN=/usr/share/man/man1
    BIN=/usr/bin
    update-alternatives --install \
	$BIN/vncviewer       vncviewer       $BIN/xvnc4viewer 75 \
	--slave \
	$MAN/vncviewer.1.gz  vncviewer.1.gz  $MAN/xvnc4viewer.1.gz \
	--slave \
	$MAN/xvncviewer.1.gz xvncviewer.1.gz $MAN/xvnc4viewer.1.gz \
	--slave \
	$BIN/xvncviewer      xvncviewer      $BIN/xvnc4viewer
fi

#DEBHELPER#

exit 0
