.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH NSPLUGINWRAPPER 1 "September 2, 2007"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
nspluginwrapper \- tool to manage nspluginwrapper-wrapped plugins
.SH SYNOPSIS
.B nspluginwrapper
.RI [ options ]
.SH DESCRIPTION
This manual page documents briefly the 
.B nspluginwrapper
command.
.PP
\fBnspluginwrapper\fP is a compatibility layer to allow the usage of non-native
plugins in a web browser supporting the Netscape 4 plugin API (NPAPI).
.SH OPTIONS
A summary of options is included below.
.TP
.B \-h
Display help and exit
.TP
.B \-i \fInpPLUGIN.so\fP
Install wrapper for npPLUGIN.so into the mozilla plugins directory
.TP
.B \-r \fI/path/to/npwrapper.npPLUGIN.so\fP
Remove the wrapper for npPLUGIN.so
.TP
.B \-u \fInpPLUGIN.so\fP
Update the plugin wrapper for npPLUGIN.so
.TP
.B \-a
Set automatic mode for plugins discovery - overrides \-i and \-u to automatically determine plugins installed
.TP
.B \-l
List plugins currently installed
.TP
.B \-n
Do not create or remove any Debian browser-specific symlinks upon installation
or removal of plugin wrappers.
.TP
.B \-v
Show verbose messages
.SH AUTHOR
nspluginwrapper was written by Gwenole Beauchesne <gb.public@free.fr>.
.PP
This manual page was written by Rob Andrews <rob@choralone.org>,
for the Debian project (but may be used by others).
