Document: qvd-wat
Title: Debian qvd-wat Manual
Author: <insert document author here>
Abstract: This manual describes what qvd-wat is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/qvd-wat/qvd-wat.sgml.gz

Format: postscript
Files: /usr/share/doc/qvd-wat/qvd-wat.ps.gz

Format: text
Files: /usr/share/doc/qvd-wat/qvd-wat.text.gz

Format: HTML
Index: /usr/share/doc/qvd-wat/html/index.html
Files: /usr/share/doc/qvd-wat/html/*.html
