#!/bin/sh

pkill perl
sleep 2

#perl -Mlib::glob=*/lib QVD-L7R/bin/qvd-l7rd
/usr/lib/qvd/bin/perl -Mlib::glob=*/lib QVD-HKD/bin/qvd-hkd
#perl -Mlib::glob=*/lib QVD-Admin-Web/script/qvd_admin_web_server.pl &
