#!/usr/lib/qvd/bin/perl

use warnings;
use strict;

use QVD::Config;
use QVD::Config::Core qw(core_cfg set_core_cfg);
use Linux::USBIP;

BEGIN {
    $QVD::Log::DAEMON_NAME = 'vma-slaveserver';

}

use QVD::Log;
INFO "Slave server started";
$SIG{__WARN__} = sub { WARN "@_"; };

# Some parameters
my $socket = fileno STDIN;
my $run_path = core_cfg("path.run");

# Check nxagent is my parent
DEBUG "Parent pid: ".getppid;
open my $ppid_file , '<',"$run_path/nxagent.pid" or warn "No nxagent pid";
my $ppid = <$ppid_file>;
close $ppid_file or DEBUG "Couldn't close $ppid_file: $!";
chomp $ppid;
getppid == $ppid or LOGDIE "Won't exec if I'm not nxagent's child";

# Now do my job
DEBUG "Reading device data";

my $data = <STDIN>;
$data or die "No device to attach";
chomp $data;

my ($devid, $speed) = split(' ',$data);

DEBUG "Attaching with Device Data: $data";

my $usbip = Linux::USBIP->new();

DEBUG "usbip->attach($socket, $devid, $speed)";
$usbip->attach($socket, $devid, $speed) or die "Couldn't import device: ".$usbip->{error_msg};

INFO "Device connected";
