.TH NXAGENT 1
.SH NAME
nxagent \- A helper application for NoMachine NX.
.SH SYNOPSIS
.B nxagent
.I "[options]"
.SH DESCRIPTION
.B nxagent
nxagent is a X server for remote access. It implements a very efficient
compression of the X11 protocol. This increases performance when
using X applications over a network, providing a near local experience.
.
nxagent should not be used alone. Look for qtnx and FreeNX.
.SH OPTIONS
.TP
.B \--help
Lists all options

.SH CONTACT
Informations can be found on http://freenx.berlios.de/.

.SH AUTHOR
This manual page was written by Per Hansen <spamhans@yahoo.de>,
and modified by Marcelo Boveto Shima <marceloshima@gmail.com>
