build:

clean:

install:
	mkdir -p $(DESTDIR)/usr/share/pixmaps
	cp pixmaps/* $(DESTDIR)/usr/share/pixmaps
	mkdir -p $(DESTDIR)/usr/share/applications
	cp qvd-client.desktop $(DESTDIR)/usr/share/applications

